const bcrypt = require("bcrypt");
const saltRounds = 10;

exports.seed = function (knex) {
  return knex("users")
    .del()
    .then(() => knex.raw("ALTER TABLE users AUTO_INCREMENT = 1000"))
    .then(() =>
      knex("users").insert([
        // SUPERADMIN usuarios
        {
          user_complete_name: "Admin Sistema Principal",
          user_email: "superadmin-1@gmail.com",
          user_dni: "20123456",
          user_phone: "+541112345678",
          user_role: "superadmin",
          user_password: bcrypt.hashSync("Superfast1-2026", saltRounds),
          user_status: true,
          company_id: null,
        },
        {
          user_complete_name: "Jorge Ruanova",
          user_email: "jruanova.dev@gmail.com",
          user_dni: "20987654",
          user_phone: "+541198765432",
          user_role: "superadmin",
          user_password: bcrypt.hashSync("123456", saltRounds),
          user_status: true,
          company_id: null,
        },
        {
          user_complete_name: "Admin Sistema Secundario",
          user_email: "superadmin-2@gmail.com",
          user_dni: "20345678",
          user_phone: "+541154321098",
          user_role: "superadmin",
          user_password: bcrypt.hashSync("Superfast2-2026", saltRounds),
          user_status: true,
          company_id: null,
        },

        // Consorcio Belgrano (company_id: 1000)
        {
          user_complete_name: "Luis Gómez",
          user_email: "owner@gmail.com",
          user_dni: "30123456",
          user_phone: "+541112345601",
          user_role: "owner",
          user_password: bcrypt.hashSync("123456", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "María Rodríguez",
          user_email: "operador-1@gmail.com",
          user_dni: "30123457",
          user_phone: "+541112345602",
          user_role: "operador",
          user_password: bcrypt.hashSync("123456", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Carlos Fernández",
          user_email: "operador-2@yahoo.com",
          user_dni: "30123458",
          user_phone: "+541112345603",
          user_role: "operador",
          user_password: bcrypt.hashSync("Consorcio-3-operador-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Ana Martínez",
          user_email: "profesional-1@gmail.com",
          user_dni: "30123459",
          user_phone: "+541112345604",
          user_role: "profesional",
          user_password: bcrypt.hashSync("123456", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Diego Sánchez",
          user_email: "profesional-2@gmail.com",
          user_dni: "30123460",
          user_phone: "+541112345605",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-02-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Laura Pérez",
          user_email: "profesional-3@gmail.com",
          user_dni: "30123461",
          user_phone: "+541112345606",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-03-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Roberto González",
          user_email: "profesional-4@gmail.com",
          user_dni: "30123462",
          user_phone: "+541112345607",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-04-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Sofía López",
          user_email: "profesional-5@gmail.com",
          user_dni: "30123463",
          user_phone: "+541112345608",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-05-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Martín Torres",
          user_email: "profesional-6@gmail.com",
          user_dni: "30123464",
          user_phone: "+541112345609",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-06-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Valentina Díaz",
          user_email: "profesional-7@gmail.com",
          user_dni: "30123465",
          user_phone: "+541112345610",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-07-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },
        {
          user_complete_name: "Fernando Romero",
          user_email: "profesional-8@gmail.com",
          user_dni: "30123466",
          user_phone: "+541112345611",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Consorcio-07-prof-2026", saltRounds),
          user_status: true,
          company_id: 1000,
        },

        // Davinci (company_id: 1001)
        {
          user_complete_name: "Camila Álvarez",
          user_email: "owner-davinci@gmail.com",
          user_dni: "40123456",
          user_phone: "+541198765401",
          user_role: "owner",
          user_password: bcrypt.hashSync("Davinci-1-owner-2026", saltRounds),
          user_status: true,
          company_id: 1001,
        },
        {
          user_complete_name: "Pablo Moreno",
          user_email: "davinci-operador@outlook.com",
          user_dni: "40123457",
          user_phone: "+541198765402",
          user_role: "operador",
          user_password: bcrypt.hashSync("Davinci-2-operador-2026", saltRounds),
          user_status: true,
          company_id: 1001,
        },
        {
          user_complete_name: "Julieta Ruiz",
          user_email: "profesional-dv-1@gmail.com",
          user_dni: "40123458",
          user_phone: "+541198765403",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Profesional-01-prof-2026", saltRounds),
          user_status: true,
          company_id: 1001,
        },
        {
          user_complete_name: "Lucía Herrera",
          user_email: "profesional-dv-2@gmail.com",
          user_dni: "40123459",
          user_phone: "+541198765404",
          user_role: "profesional",
          user_password: bcrypt.hashSync("Profesional-02-prof-2026", saltRounds),
          user_status: true,
          company_id: 1001,
        },

        // Electronica Moreno (company_id: 1002)
        {
          user_complete_name: "Roberto Moreno",
          user_email: "elec-moreno-1@gmail.com",
          user_dni: "50123456",
          user_phone: "+541145678901",
          user_role: "owner",
          user_password: bcrypt.hashSync("elecmoreno-1-owner-2026", saltRounds),
          user_status: true,
          company_id: 1002,
        },
        {
          user_complete_name: "Patricia García",
          user_email: "elec-moreno-op-1@outlook.com",
          user_dni: "50123457",
          user_phone: "+541145678902",
          user_role: "operador",
          user_password: bcrypt.hashSync("elecmoreno-2-operador-2026", saltRounds),
          user_status: true,
          company_id: 1002,
        },
        {
          user_complete_name: "Gabriel Martínez",
          user_email: "em-profesional-1@gmail.com",
          user_dni: "50123458",
          user_phone: "+541145678903",
          user_role: "profesional",
          user_password: bcrypt.hashSync("elecmoreno-01-prof-2026", saltRounds),
          user_status: true,
          company_id: 1002,
        },
        {
          user_complete_name: "Elena Sánchez",
          user_email: "em-profesional-2@gmail.com",
          user_dni: "50123459",
          user_phone: "+541145678904",
          user_role: "profesional",
          user_password: bcrypt.hashSync("elecmoreno-02-prof-2026", saltRounds),
          user_status: true,
          company_id: 1002,
        },
        {
          user_complete_name: "Nicolás Pérez",
          user_email: "em-profesional-3@gmail.com",
          user_dni: "50123460",
          user_phone: "+541145678905",
          user_role: "profesional",
          user_password: bcrypt.hashSync("elecmoreno-03-prof-2026", saltRounds),
          user_status: true,
          company_id: 1002,
        },

        // Renovar Gym (company_id: 1003)
        {
          user_complete_name: "Luis López",
          user_email: "luis.l@gmail.com",
          user_dni: "60123456",
          user_phone: "+541156789012",
          user_role: "owner",
          user_password: bcrypt.hashSync("ren-gym-1-owner-2026", saltRounds),
          user_status: true,
          company_id: 1003,
        },
        {
          user_complete_name: "María González",
          user_email: "ren-gym-1@gmail.com",
          user_dni: "60123457",
          user_phone: "+541156789013",
          user_role: "operador",
          user_password: bcrypt.hashSync("ren-gym-2-operador-2026", saltRounds),
          user_status: true,
          company_id: 1003,
        },
        {
          user_complete_name: "Carlos Fernández",
          user_email: "ren-profesional-1@gmail.com",
          user_dni: "60123458",
          user_phone: "+541156789014",
          user_role: "profesional",
          user_password: bcrypt.hashSync("ren-gym-01-prof-2026", saltRounds),
          user_status: true,
          company_id: 1003,
        },
        {
          user_complete_name: "Andrea Rodríguez",
          user_email: "ren-profesional-2@gmail.com",
          user_dni: "60123459",
          user_phone: "+541156789015",
          user_role: "profesional",
          user_password: bcrypt.hashSync("ren-gym-02-prof-2026", saltRounds),
          user_status: true,
          company_id: 1003,
        },
        {
          user_complete_name: "Marcelo Torres",
          user_email: "ren-profesional-3@gmail.com",
          user_dni: "60123460",
          user_phone: "+541156789016",
          user_role: "profesional",
          user_password: bcrypt.hashSync("ren-gym-03-prof-2026", saltRounds),
          user_status: true,
          company_id: 1003,
        },
        {
          user_complete_name: "Florencia Díaz",
          user_email: "ren-profesional-4@gmail.com",
          user_dni: "60123461",
          user_phone: "+541156789017",
          user_role: "profesional",
          user_password: bcrypt.hashSync("ren-gym-02-prof-2026", saltRounds),
          user_status: true,
          company_id: 1003,
        },
      ])
    );
};
